---

git_conf:
  - name: user.name
    value: Fly me to the moon

  - name: user.email
    value: git@bigly.dog

  - name: diff.algorithm
    value: minimal

  - name: alias.tm
    value: time-machine

  - name: alias.ded
    value: dead
